import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import Skills from "../skills/page"
import Timeline from "../timeline/page"
import Project from "../project/page"
import Resume from "../resume/page"
import Contact from "../contact/page"
import About from '../about/page'




const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function home({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
     
        {children}
        <About/>
        {/* <TypeEffect/> */}
        <Skills/>
        <Timeline/>
        <Project/>
        <Resume/>
        <Contact/>
        </body>
    </html>
  )
}
